Repository nlyra/SystemsEngineeringToolkit, pull requests merged in 2021-06, with the labels that each got.

#82 80 upload capabilities
  frontend/toolkit-webapp/README.md
  frontend/toolkit-webapp/package-lock.json
  frontend/toolkit-webapp/package.json
  frontend/toolkit-webapp/src/pages/CourseCreatorNewCourse.js
  frontend/toolkit-webapp/src/pages/Dashboard.js
  server/package-lock.json
  server/package.json
  server/routes/courses.js
  server/routes/fileMulter.js
  server/server.js
Labels: enhancement

#89 49 course creator manager
  frontend/toolkit-webapp/README.md
  frontend/toolkit-webapp/package-lock.json
  frontend/toolkit-webapp/src/components/CourseInfoEditButton.js
  frontend/toolkit-webapp/src/components/ModuleInfoEditButton.js
  frontend/toolkit-webapp/src/pages/Course.js
  frontend/toolkit-webapp/src/pages/CourseCreatorNewCourse.js
  frontend/toolkit-webapp/src/styles/courseInfoButton.js
  server/routes/courses.js
Labels: enhancement

#93 86 page linking
  frontend/toolkit-webapp/src/App.js
  frontend/toolkit-webapp/src/components/TopNavBar.js
  frontend/toolkit-webapp/src/pages/ManageCourses.js
  frontend/toolkit-webapp/src/pages/MyCourses.js
  frontend/toolkit-webapp/src/pages/MyFiles.js
Labels: enhancement

#104 41 module creator quiz
  frontend/toolkit-webapp/package-lock.json
  frontend/toolkit-webapp/src/components/FileModule.js
  frontend/toolkit-webapp/src/components/MultipleChoiceCreator.js
  frontend/toolkit-webapp/src/components/QuizModule.js
  frontend/toolkit-webapp/src/components/TrueOrFalseCreator.js
  frontend/toolkit-webapp/src/pages/ModuleCreator.js
  server/routes/courses.js
Labels: enhancement

#118 fix issue with modules not showing content
  server/routes/courses.js
Labels: bug

#107 85 category tags
  frontend/toolkit-webapp/src/pages/CourseCreatorNewCourse.js
  frontend/toolkit-webapp/src/styles/courseStyle.js
  server/models/categories.js
  server/models/course.js
  server/routes/categories.js
  server/server.js
Labels: enhancement

#113 41 module creator quiz
  frontend/toolkit-webapp/src/components/MultipleChoiceCreator.js
  frontend/toolkit-webapp/src/components/QuizCreatorModule.js
  frontend/toolkit-webapp/src/components/QuizModule.js
  frontend/toolkit-webapp/src/components/TrueOrFalseCreator.js
  frontend/toolkit-webapp/src/pages/ModuleCreator.js
Labels: enhancement

#124 77 forgot password page
  frontend/toolkit-webapp/src/App.js
  frontend/toolkit-webapp/src/components/TopNavBar.js
  frontend/toolkit-webapp/src/config.json
  frontend/toolkit-webapp/src/pages/ForgotPassword.js
  frontend/toolkit-webapp/src/pages/ResetPassword.js
  frontend/toolkit-webapp/src/styles/loginStyle.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
  server/routes/courses.js
Labels: enhancement

#136 added the new quiz
  frontend/toolkit-webapp/src/components/QuizModule.js
  frontend/toolkit-webapp/src/pages/Course.js
  frontend/toolkit-webapp/src/pages/ModuleCreator.js
  frontend/toolkit-webapp/src/styles/quizModuleStyle.js
  server/routes/courses.js
Labels: enhancement

#138 116 admin page
  frontend/toolkit-webapp/package-lock.json
  frontend/toolkit-webapp/package.json
  frontend/toolkit-webapp/src/App.js
  frontend/toolkit-webapp/src/components/AdminCategoriesTab.js
  frontend/toolkit-webapp/src/components/AdminCoursesTab.js
  frontend/toolkit-webapp/src/components/AdminUsersTab.js
  frontend/toolkit-webapp/src/components/TopNavBar.js
  frontend/toolkit-webapp/src/config.json
  frontend/toolkit-webapp/src/pages/AdminDashboard.js
  frontend/toolkit-webapp/src/pages/CourseCreatorNewCourse.js
  server/config.json
  server/models/user.js
  server/public/60c2ce28463c28321000136c/200px-Question_mark_(black).svg.png
  server/routes/admin.js
  server/routes/auth.js
  server/routes/courses.js
  server/server.js
Labels: enhancement

#140 134 course image edit
  frontend/toolkit-webapp/src/config.json
  frontend/toolkit-webapp/src/pages/Course.js
  frontend/toolkit-webapp/src/pages/CourseCreatorNewCourse.js
  frontend/toolkit-webapp/src/pages/ManageMyCourses.js
  frontend/toolkit-webapp/src/styles/courseStyle.js
  server/config.json
  server/public/60c963d31004b923701b55c8/grade.PNG
  server/public/example.PNG
  server/routes/categories.js
  server/routes/courses.js
  server/routes/fileMulter.js
Labels: enhancement

#147 141 modules upgrade
  frontend/toolkit-webapp/package-lock.json
  frontend/toolkit-webapp/src/components/QuizModule.js
  frontend/toolkit-webapp/src/config.json
  frontend/toolkit-webapp/src/pages/Course.js
  frontend/toolkit-webapp/src/pages/MyCourses.js
  frontend/toolkit-webapp/src/styles/courseStyle.js
  frontend/toolkit-webapp/src/styles/quizModuleStyle.js
  server/models/course.js
  server/models/user.js
  server/routes/courses.js
Labels: enhancement

#143 142 delete module
  frontend/toolkit-webapp/src/components/ModuleInfoEditButton.js
  frontend/toolkit-webapp/src/config.json
  frontend/toolkit-webapp/src/pages/Course.js
  frontend/toolkit-webapp/src/styles/courseStyle.js
  server/routes/courses.js
Labels: enhancement

#150 135 my profile
  frontend/toolkit-webapp/src/components/TopNavBar.js
  frontend/toolkit-webapp/src/config.json
  frontend/toolkit-webapp/src/pages/MyCourses.js
  server/routes/courses.js
  server/routes/settings.js
  server/server.js
Labels: enhancement

#149 145 admin page upgrades
  frontend/toolkit-webapp/src/components/AdminCategoriesTab.js
  frontend/toolkit-webapp/src/components/AdminCoursesTab.js
  frontend/toolkit-webapp/src/components/AdminUsersTab.js
  frontend/toolkit-webapp/src/config.json
  frontend/toolkit-webapp/src/pages/AdminDashboard.js
  server/models/course.js
  server/routes/admin.js
  server/routes/courses.js
Labels: enhancement

#155 Search bar now works with the category arrays
  server/routes/courses.js
Labels: enhancement

#146 eliminated as many unused dependencies as I could
  frontend/toolkit-webapp/package-lock.json
  frontend/toolkit-webapp/package.json
Labels: removal

#163 158 fixing upload image issue
  frontend/toolkit-webapp/src/config.json
  frontend/toolkit-webapp/src/pages/Course.js
  frontend/toolkit-webapp/src/pages/CourseCreatorNewCourse.js
  server/models/course.js
  server/public/60aeaa0574ee92fee31e4b02/engineering101.jpg
  server/public/60b6f0cae78b5440c428659d/radar_logo.jpg
  server/public/60c409db21c6d84518d91bb2/checkmark.png
  server/public/60c963d31004b923701b55c8/grade.PNG
  server/public/60cb5e29a389673be19a9148/knit_logo.jpg
  server/public/60d4a11eb34b866f84ec5358/java-logo.png
  server/public/60d4a37cb34b866f84ec535a/Strategy_logo.jpg
  server/public/60d4a425b34b866f84ec535e/hardware_logo.png
  server/public/60d4a501b34b866f84ec5360/cybersecurity_logo.jpg
  server/public/sn&i.PNG
  server/routes/courses.js
  server/routes/fileMulter.js
Labels: enhancement

#162 161 profile page upgrades
  frontend/toolkit-webapp/src/components/TopNavBar.js
  server/routes/courses.js
  server/routes/settings.js
Labels: enhancement
