Repository nlyra/SystemsEngineeringToolkit, pull requests merged in 2021-07, with the labels that each got.

#167 Roles
  frontend/toolkit-webapp/src/components/AdminCategoriesTab.js
  frontend/toolkit-webapp/src/components/AdminCoursesTab.js
  frontend/toolkit-webapp/src/components/AdminUsersTab.js
  frontend/toolkit-webapp/src/components/TopNavBar.js
  frontend/toolkit-webapp/src/config.json
  frontend/toolkit-webapp/src/pages/AdminDashboard.js
  frontend/toolkit-webapp/src/pages/Course.js
  frontend/toolkit-webapp/src/pages/CourseCreatorNewCourse.js
  frontend/toolkit-webapp/src/pages/ManageMyCourses.js
  frontend/toolkit-webapp/src/pages/ModuleCreator.js
  frontend/toolkit-webapp/src/pages/ModuleEditor.js
  frontend/toolkit-webapp/src/pages/ModuleManager.js
  server/package-lock.json
  server/routes/admin.js
  server/routes/auth.js
  server/routes/categories.js
  server/routes/courses.js
  server/routes/fileMulter.js
Labels: enhancement

#171 168 log out
  frontend/toolkit-webapp/package-lock.json
  frontend/toolkit-webapp/src/components/TopNavBar.js
Labels: enhancement

#175 62 endless scrolling
  frontend/toolkit-webapp/package-lock.json
  frontend/toolkit-webapp/package.json
  frontend/toolkit-webapp/src/css/dashboard.css
  frontend/toolkit-webapp/src/css/scrollbar.css
  frontend/toolkit-webapp/src/pages/Dashboard.js
  frontend/toolkit-webapp/src/pages/ManageMyCourses.js
  frontend/toolkit-webapp/src/pages/MyCourses.js
  frontend/toolkit-webapp/src/styles/dashboardStyle.js
  frontend/toolkit-webapp/src/styles/moduleStyle.js
  server/routes/courses.js
Labels: enhancement

#173 Completed Profile Upgrades
  frontend/toolkit-webapp/src/components/TopNavBar.js
  frontend/toolkit-webapp/src/config.json
  server/models/user.js
  server/routes/settings.js
Labels: enhancement

#164 Module File Storing Completed
  frontend/toolkit-webapp/src/config.json
  frontend/toolkit-webapp/src/pages/ModuleCreator.js
  frontend/toolkit-webapp/src/pages/ModuleEditor.js
  server/public/60d8a121620f345124f771ab/app.PNG
  server/public/60da2d71d84df9a253b57d4d/moduleData/LyraResumeJune2021.pdf
  server/routes/courses.js
  server/routes/fileMulter.js
Labels: bug

#169 166-course_upgrades
  frontend/toolkit-webapp/src/App.js
  frontend/toolkit-webapp/src/components/TopNavBar.js
  frontend/toolkit-webapp/src/pages/Course.js
  frontend/toolkit-webapp/src/pages/CourseCreatorNewCourse.js
  frontend/toolkit-webapp/src/pages/MyFiles.js
  frontend/toolkit-webapp/src/styles/courseCreatorStyle.js
  frontend/toolkit-webapp/src/styles/courseStyle.js
  server/models/course.js
  server/public/60db15047299e4109c95618c/engineering101.jpg
  server/public/60db158220678b1e9454f4af/checkmark.png
  server/routes/courses.js
Labels: enhancement

#182 176 course creation upgrades
  frontend/toolkit-webapp/src/components/AdminCoursesTab.js
  frontend/toolkit-webapp/src/components/CourseInfoEditButton.js
  frontend/toolkit-webapp/src/config.json
  frontend/toolkit-webapp/src/pages/Course.js
  frontend/toolkit-webapp/src/pages/CourseCreatorNewCourse.js
  frontend/toolkit-webapp/src/styles/courseStyle.js
  server/models/course.js
  server/public/60e4fcd4c5d9341e3c0a7223/checkmark.png
  server/routes/admin.js
  server/routes/courses.js
Labels: enhancement

#186 181 file uploads fix
  frontend/toolkit-webapp/src/pages/ModuleCreator.js
  server/routes/courses.js
  server/routes/fileMulter.js
Labels: bug

#191 165 Added role tool tips
  frontend/toolkit-webapp/src/components/TopNavBar.js
Labels: enhancement

#200 Remade Tooltips
  frontend/toolkit-webapp/src/components/TopNavBar.js
Labels: bug

#188 Cover Image Updates Correctly if Unchanged
  frontend/toolkit-webapp/src/pages/Course.js
  server/public/60e5136c128ad02f28a9479b/java.gif
  server/public/60e5136c128ad02f28a9479b/moduleData/roleCreation.txt
  server/routes/courses.js
Labels: bug

#184 183 token expiration
  frontend/toolkit-webapp/src/components/AdminCategoriesTab.js
  frontend/toolkit-webapp/src/components/AdminCoursesTab.js
  frontend/toolkit-webapp/src/components/AdminUsersTab.js
  frontend/toolkit-webapp/src/components/QuizModule.js
  frontend/toolkit-webapp/src/components/TopNavBar.js
  frontend/toolkit-webapp/src/pages/Course.js
  frontend/toolkit-webapp/src/pages/CourseCreatorNewCourse.js
  frontend/toolkit-webapp/src/pages/Dashboard.js
  frontend/toolkit-webapp/src/pages/ManageMyCourses.js
  frontend/toolkit-webapp/src/pages/ModuleCreator.js
  frontend/toolkit-webapp/src/pages/ModuleEditor.js
  frontend/toolkit-webapp/src/pages/ModuleManager.js
  frontend/toolkit-webapp/src/pages/MyCourses.js
  server/routes/admin.js
  server/routes/auth.js
  server/routes/courses.js
  server/routes/settings.js
Labels: bug

#206 Dev into main
  frontend/toolkit-webapp/src/components/AdminCategoriesTab.js
  frontend/toolkit-webapp/src/components/AdminCoursesTab.js
  frontend/toolkit-webapp/src/components/AdminUsersTab.js
  frontend/toolkit-webapp/src/components/QuizModule.js
  frontend/toolkit-webapp/src/components/TopNavBar.js
  frontend/toolkit-webapp/src/pages/Course.js
  frontend/toolkit-webapp/src/pages/CourseCreatorNewCourse.js
  frontend/toolkit-webapp/src/pages/Dashboard.js
  frontend/toolkit-webapp/src/pages/ManageMyCourses.js
  frontend/toolkit-webapp/src/pages/ModuleCreator.js
  frontend/toolkit-webapp/src/pages/ModuleEditor.js
  frontend/toolkit-webapp/src/pages/ModuleManager.js
  frontend/toolkit-webapp/src/pages/MyCourses.js
  server/routes/admin.js
  server/routes/auth.js
  server/routes/courses.js
  server/routes/settings.js
Labels: Dev into Main

#207 122 update course info frontend
  frontend/toolkit-webapp/src/App.js
  frontend/toolkit-webapp/src/pages/Course.js
  frontend/toolkit-webapp/src/pages/EditCourse.js
  server/package-lock.json
  server/public/60ec9b0fd02b3f0b24f9be85/UserRolesToolTip.png
  server/routes/courses.js
Labels: enhancement

#201 Made several changes to Profile And Dashboard
  frontend/toolkit-webapp/src/components/TopNavBar.js
  frontend/toolkit-webapp/src/pages/Dashboard.js
  frontend/toolkit-webapp/src/pages/ManageMyCourses.js
  frontend/toolkit-webapp/src/pages/MyCourses.js
  frontend/toolkit-webapp/src/styles/dashboardStyle.js
  frontend/toolkit-webapp/src/styles/myCoursesStyle.js
Labels: enhancement

#211 209 admin super creator
  frontend/toolkit-webapp/src/pages/ModuleCreator.js
  frontend/toolkit-webapp/src/pages/ModuleEditor.js
  server/routes/courses.js
Labels: enhancement

#212 210 dev fixes
  frontend/toolkit-webapp/src/pages/CourseCreatorNewCourse.js
  frontend/toolkit-webapp/src/pages/Dashboard.js
  frontend/toolkit-webapp/src/pages/ManageMyCourses.js
  frontend/toolkit-webapp/src/pages/MyCourses.js
  server/public/Goristro.jpg
  server/public/gameboard.PNG
  server/routes/courses.js
  server/routes/fileMulter.js
Labels: bug

#213 174 dockerizing
  docker-compose.yml
  frontend/package-lock.json
  frontend/toolkit-webapp/.dockerignore
  frontend/toolkit-webapp/Dockerfile
  frontend/toolkit-webapp/src/components/TopNavBar.js
  frontend/toolkit-webapp/src/config.json
  frontend/toolkit-webapp/src/pages/Course.js
  frontend/toolkit-webapp/src/pages/CourseCreatorNewCourse.js
  frontend/toolkit-webapp/src/pages/Dashboard.js
  frontend/toolkit-webapp/src/pages/Login.js
  frontend/toolkit-webapp/src/pages/ManageMyCourses.js
  frontend/toolkit-webapp/src/pages/ModuleCreator.js
  frontend/toolkit-webapp/src/pages/ModuleEditor.js
  frontend/toolkit-webapp/src/pages/MyCourses.js
  package-lock.json
  server/.dockerignore
  server/Dockerfile
  server/config.json
  server/package-lock.json
  server/routes/auth.js
  server/routes/courses.js
  server/routes/fileMulter.js
Labels: enhancement
